"""SharePoint connection settings — credential resolution and its guard.

The certificate private key reaches the connector one of two ways, and an
admin picks which on the connection form:

* **their own** — stored encrypted in this connection's vault slot;
* **the server's** — named by ``config.cert_private_key_env``, whose value the
  deployment injects into the process environment (on a VM, the startup script
  writes it into ``/opt/agnes/.env`` from Secret Manager).

Vault wins when both are present, mirroring
``connectors.snowflake.settings._resolve_row_secret``.

The env NAME is admin-writable, so it is untrusted exactly like a request
body: without the shared allowlist guard
(``src.orchestrator_security.is_token_env_allowed``) an admin could point
``cert_private_key_env`` at ``ANTHROPIC_API_KEY`` or ``JWT_SECRET_KEY`` and
have Agnes hand that value to a connector as the SharePoint credential. That
is the same hole the second-round RBAC review closed for Snowflake and
Databricks; these tests keep it closed here from the first commit.
"""

from __future__ import annotations

import pytest

from connectors.sharepoint.settings import (
    SHAREPOINT_CERT_PRIVATE_KEY_ENV,
    SharePointSettingsError,
    resolve_sharepoint_settings,
)

PEM_FROM_ENV = "-----BEGIN PRIVATE KEY-----\nfrom-env\n-----END PRIVATE KEY-----"
PEM_FROM_VAULT = "-----BEGIN PRIVATE KEY-----\nfrom-vault\n-----END PRIVATE KEY-----"


def _row(**config_overrides):
    config = {"tenant_id": "b6386aaa-tenant", "client_id": "6ef04383-client"}
    config.update(config_overrides)
    return {"id": "conn-1", "source_type": "sharepoint", "name": "corp-files", "config": config}


@pytest.fixture
def no_vault(monkeypatch):
    """No vault secret for this connection — isolates the env path."""
    monkeypatch.setattr("connectors.sharepoint.settings._vault_secret", lambda connection_id: None, raising=False)
    monkeypatch.delenv(SHAREPOINT_CERT_PRIVATE_KEY_ENV, raising=False)
    monkeypatch.delenv("AGNES_REMOTE_ATTACH_TOKEN_ENVS", raising=False)


def test_identity_fields_come_from_the_row(no_vault, monkeypatch):
    monkeypatch.setenv(SHAREPOINT_CERT_PRIVATE_KEY_ENV, PEM_FROM_ENV)
    settings = resolve_sharepoint_settings(_row(cert_private_key_env=SHAREPOINT_CERT_PRIVATE_KEY_ENV))

    assert settings.tenant_id == "b6386aaa-tenant"
    assert settings.client_id == "6ef04383-client"


def test_server_certificate_resolves_from_the_named_env_var(no_vault, monkeypatch):
    monkeypatch.setenv(SHAREPOINT_CERT_PRIVATE_KEY_ENV, PEM_FROM_ENV)
    settings = resolve_sharepoint_settings(_row(cert_private_key_env=SHAREPOINT_CERT_PRIVATE_KEY_ENV))

    assert settings.private_key == PEM_FROM_ENV
    assert settings.credential_source == "env"


def test_the_default_env_name_needs_no_config_entry(no_vault, monkeypatch):
    """An admin who picks "the server's certificate" without naming a variable
    gets the documented default, so the common case needs no typing."""
    monkeypatch.setenv(SHAREPOINT_CERT_PRIVATE_KEY_ENV, PEM_FROM_ENV)
    settings = resolve_sharepoint_settings(_row())

    assert settings.private_key == PEM_FROM_ENV
    assert settings.credential_source == "env"


def test_admin_supplied_certificate_wins_over_the_server_one(monkeypatch):
    monkeypatch.setattr(
        "connectors.sharepoint.settings._vault_secret",
        lambda connection_id: PEM_FROM_VAULT,
        raising=False,
    )
    monkeypatch.setenv(SHAREPOINT_CERT_PRIVATE_KEY_ENV, PEM_FROM_ENV)

    settings = resolve_sharepoint_settings(_row(cert_private_key_env=SHAREPOINT_CERT_PRIVATE_KEY_ENV))

    assert settings.private_key == PEM_FROM_VAULT
    assert settings.credential_source == "vault"


def test_an_unrelated_env_name_is_refused_not_read(no_vault, monkeypatch):
    """The guard that matters: a connection may not name an arbitrary secret."""
    monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-ant-should-never-be-read")

    with pytest.raises(SharePointSettingsError) as excinfo:
        resolve_sharepoint_settings(_row(cert_private_key_env="ANTHROPIC_API_KEY"))

    message = str(excinfo.value)
    assert "ANTHROPIC_API_KEY" in message
    assert "sk-ant-should-never-be-read" not in message


def test_a_structurally_invalid_env_name_is_refused(no_vault):
    with pytest.raises(SharePointSettingsError):
        resolve_sharepoint_settings(_row(cert_private_key_env="not a valid name"))


def test_a_named_variable_that_is_not_set_says_so(no_vault):
    """The VM's .env is regenerated by a startup script under ignore_changes,
    so "the admin picked it but the deployment never injected it" is the
    likely failure — it has to name the variable, not fail vaguely."""
    with pytest.raises(SharePointSettingsError) as excinfo:
        resolve_sharepoint_settings(_row(cert_private_key_env=SHAREPOINT_CERT_PRIVATE_KEY_ENV))

    assert SHAREPOINT_CERT_PRIVATE_KEY_ENV in str(excinfo.value)


def test_missing_identity_fields_are_reported_before_any_credential_lookup(no_vault):
    with pytest.raises(SharePointSettingsError) as excinfo:
        resolve_sharepoint_settings({"id": "conn-1", "source_type": "sharepoint", "config": {}})

    assert "tenant_id" in str(excinfo.value)


# ---------------------------------------------------------------------------
# credential_set_at — the source card's certificate row (spec §13.2) shows
# WHEN a vault credential was set, never the value.
# ---------------------------------------------------------------------------


def test_vault_credential_carries_its_set_date(monkeypatch):
    import datetime

    stamp = datetime.datetime(2026, 8, 20, 12, 0, 0, tzinfo=datetime.timezone.utc)
    monkeypatch.setattr(
        "connectors.sharepoint.settings._vault_secret",
        lambda connection_id: PEM_FROM_VAULT,
        raising=False,
    )
    monkeypatch.setattr(
        "connectors.sharepoint.settings._vault_secret_updated_at",
        lambda connection_id: stamp,
        raising=False,
    )

    settings = resolve_sharepoint_settings(_row())

    assert settings.credential_source == "vault"
    assert settings.credential_set_at == stamp


def test_env_credential_has_no_set_date(no_vault, monkeypatch):
    """An env var carries no timestamp of its own — the field stays honest
    (``None``) rather than inventing one from, say, process start time."""
    monkeypatch.setenv(SHAREPOINT_CERT_PRIVATE_KEY_ENV, PEM_FROM_ENV)
    settings = resolve_sharepoint_settings(_row())

    assert settings.credential_source == "env"
    assert settings.credential_set_at is None


def test_the_repos_string_stamp_becomes_a_real_datetime(monkeypatch):
    """The test above monkeypatches ``_vault_secret_updated_at`` itself, so it
    never crosses the seam that actually matters: BOTH ``connection_secrets``
    repos (``app/secrets_vault.py`` and its ``_pg`` sibling) return
    ``str(row[0])``, while ``credential_set_at`` is annotated
    ``Optional[datetime]`` and its one consumer — the source card's
    certificate cell — calls ``.isoformat()`` on it. A string reached that
    call, raised ``AttributeError`` into a handler that swallows it, and a
    working vault certificate was rendered as unconfigured.
    """
    import datetime

    class _StringRepo:
        def updated_at(self, connection_id):
            # Exactly what both backends produce: str() of a timestamp.
            return "2026-08-20 12:00:00"

    monkeypatch.setattr(
        "connectors.sharepoint.settings._vault_secret",
        lambda connection_id: PEM_FROM_VAULT,
        raising=False,
    )
    monkeypatch.setattr("src.repositories.connection_secrets_repo", lambda: _StringRepo())

    settings = resolve_sharepoint_settings(_row())

    assert settings.credential_source == "vault"
    assert isinstance(settings.credential_set_at, datetime.datetime)
    assert settings.credential_set_at.isoformat().startswith("2026-08-20T12:00:00")


def test_an_unparseable_stamp_degrades_to_none_not_a_broken_card(monkeypatch):
    """Same posture as every other failure in this lookup: the card would
    rather show a blank set-date than lose a working credential."""

    class _JunkRepo:
        def updated_at(self, connection_id):
            return "not a timestamp"

    monkeypatch.setattr(
        "connectors.sharepoint.settings._vault_secret",
        lambda connection_id: PEM_FROM_VAULT,
        raising=False,
    )
    monkeypatch.setattr("src.repositories.connection_secrets_repo", lambda: _JunkRepo())

    settings = resolve_sharepoint_settings(_row())

    assert settings.credential_source == "vault"
    assert settings.credential_set_at is None


def test_vault_set_date_lookup_failure_degrades_to_none(monkeypatch):
    """A raising ``connection_secrets_repo()`` (no vault configured, or a
    lookup error) must not turn a resolvable credential into a resolution
    failure — the tolerant try/except inside ``_vault_secret_updated_at``
    (same posture as ``_vault_secret`` itself) degrades to "set-date
    unknown", never propagates."""

    class _BoomRepo:
        def updated_at(self, connection_id):
            raise RuntimeError("vault unavailable")

    monkeypatch.setattr(
        "connectors.sharepoint.settings._vault_secret",
        lambda connection_id: PEM_FROM_VAULT,
        raising=False,
    )
    monkeypatch.setattr("src.repositories.connection_secrets_repo", lambda: _BoomRepo())

    settings = resolve_sharepoint_settings(_row())

    assert settings.credential_source == "vault"
    assert settings.credential_set_at is None
