"""Render RBAC-visible Ossie semantic-model documents into the read-only
local cache `agnes pull` writes to disk (Fáze 1 — "distribuce jako fyzická
cache s TTL" of the semantic-layer follow-up plan).

The live reading trio (``get_semantic_context``/``get_semantic_schema``/
``validate_semantic_query``, ``src/semantic_context.py`` +
``src/semantic_validation.py``) already exists and stays the source of
truth. This module is the missing physical-distribution half: it turns the
same document store rows into a directory an analyst/agent can read straight
off disk between ``agnes pull`` calls, without a server round trip.

Deliberately reads from the ALREADY-PARSED document (``document_json``, the
canonical Ossie shape ``{"semantic_model": [...]}`` — see
``src/semantic/document_validation.py``), never from the legacy flat tables
(``metric_definitions``/``table_registry``/``column_metadata``/
``bq_metadata_cache``) that ``src/data_semantics_scaffold.py`` reads — that
module's *reading* path predates the document-store cutover and is
out of scope here (see that module's own docstring). Only its rendering
helpers (``_dump_yaml``, ``humanize``) are reused, for byte-identical YAML
styling between the two packs.

Glossary extraction reuses ``src.semantic.projection._glossary_entries`` —
the same document-based accessor the flat-table projection uses to derive
``glossary_terms`` — rather than re-deriving the ``custom_extensions``
Agnes-vendor convention a second time.

Layout, one directory per model row (keyed by the row's own ``slug`` — not
necessarily every ``semantic_model`` entry's ``name``, though today a row
holds exactly one)::

    <slug>/
      _brief.md            prose overview + dataset/metric tables
      tables/<name>.yml     one file per dataset
      metrics/<name>.yml    one file per metric
      glossary.md           only written when the document declares terms

Every file starts with a header comment carrying ``generated_at``,
``content_hash`` (the row's own ``semantic_models.content_hash`` — reused,
never recomputed), ``source_slug`` and ``ttl_seconds``: the artifact an
agent's TTL policy (``config/claude_md_template.txt``) reads to decide
whether to trust the file or re-verify against the live
``get_semantic_context`` endpoint.

Pure — no DB access, no HTTP, no ``app.`` import — mirrors
``src/data_semantics_scaffold.py``'s own posture so it stays unit-testable
without a database.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from src.data_semantics_scaffold import _dump_yaml, humanize
from src.semantic.projection import _glossary_entries

# Fáze 1 open question #1 (semanticlayer/plan.md §5.1) — "default TTL cache
# (24h? per-source per sync schedule?)" is explicitly unresolved by product.
# 24h is a reasonable default matching this instance's typical daily sync
# cadence (`get_sync_interval()`); a per-source policy is future work, not
# blocking the physical-distribution gap this module closes.
DEFAULT_TTL_SECONDS = 24 * 60 * 60

_CACHE_NOTE = "Agnes-managed semantic-layer cache -- read-only, regenerated by `agnes pull`. Do not edit."

__all__ = ["DEFAULT_TTL_SECONDS", "render_semantic_cache"]


def _header_fields(*, generated_at: str, content_hash: str, source_slug: str, ttl_seconds: int) -> List[str]:
    return [
        f"generated_at: {generated_at}",
        f"content_hash: {content_hash or ''}",
        f"source_slug: {source_slug}",
        f"ttl_seconds: {ttl_seconds}",
        _CACHE_NOTE,
    ]


def _yaml_header(**kw: Any) -> str:
    return "".join(f"# {line}\n" for line in _header_fields(**kw))


def _md_header(**kw: Any) -> str:
    return "<!--\n" + "\n".join(_header_fields(**kw)) + "\n-->\n"


def _truncate(text: str, limit: int = 80) -> str:
    text = (text or "").replace("\n", " ").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


def _brief_body(row: Dict[str, Any], models: List[dict], datasets: List[dict], metrics: List[dict]) -> str:
    slug = row.get("slug") or ""
    name = row.get("name") or slug or humanize(slug)
    description = (row.get("description") or "").strip()
    if not description and models:
        description = (models[0].get("description") or "").strip()

    lines: List[str] = [f"# {name} — Semantic Model", ""]
    if description:
        lines += [description, ""]

    source = row.get("source") or "manual"
    source_ref = row.get("source_ref")
    lines.append(f"Source: `{source}`" + (f" (`{source_ref}`)" if source_ref else ""))
    lines.append("")

    lines += ["## Datasets", ""]
    if datasets:
        lines.append("| Dataset | Source |")
        lines.append("|---|---|")
        for d in datasets:
            lines.append(f"| `{d.get('name', '?')}` | `{d.get('source', '—')}` |")
    else:
        lines.append("_No datasets declared._")
    lines.append("")

    lines += ["## Metrics", ""]
    if metrics:
        lines.append("| Metric | Description |")
        lines.append("|---|---|")
        for m in metrics:
            desc = _truncate(m.get("description") or "")
            lines.append(f"| `{m.get('name', '?')}` | {desc or '—'} |")
    else:
        lines.append("_No metrics declared._")
    lines.append("")

    return "\n".join(lines)


def _glossary_body(entries: List[dict]) -> str:
    lines: List[str] = ["# Glossary", ""]
    for entry in entries:
        term = entry.get("term")
        if not term:
            continue
        lines.append(f"## {term}")
        definition = (entry.get("definition") or "").strip()
        if definition:
            lines += ["", definition]
        see_also = entry.get("see_also")
        if see_also:
            rendered = ", ".join(str(s) for s in see_also) if isinstance(see_also, list) else str(see_also)
            lines += ["", f"See also: {rendered}"]
        lines.append("")
    return "\n".join(lines)


def render_semantic_cache(
    rows: Optional[List[Dict[str, Any]]],
    *,
    generated_at: str,
    ttl_seconds: int = DEFAULT_TTL_SECONDS,
) -> Dict[str, str]:
    """Render ``rows`` (semantic_models rows, RBAC-filtering already applied
    by the caller — see ``app/api/semantic_models.py::semantic_models_bundle``)
    into ``{relpath: content}``.

    Every relpath is rooted at the model's own ``slug`` — the caller writes
    them under ``<workspace>/semantic/``. A row with no ``slug``, or whose
    ``document_json`` carries no ``semantic_model`` list, is skipped rather
    than raising (never-guess, never-crash posture consistent with the rest
    of this document-reading surface — ``src/semantic_context.py``,
    ``src/semantic_validation.py``).
    """
    files: Dict[str, str] = {}
    for row in rows or []:
        if not isinstance(row, dict):
            continue
        slug = (row.get("slug") or "").strip()
        if not slug:
            continue

        document_json = row.get("document_json") or {}
        raw_models = document_json.get("semantic_model") if isinstance(document_json, dict) else None
        models = [m for m in (raw_models or []) if isinstance(m, dict)]

        datasets: List[dict] = []
        metrics: List[dict] = []
        glossary: List[dict] = []
        for model in models:
            datasets.extend(d for d in (model.get("datasets") or []) if isinstance(d, dict) and d.get("name"))
            metrics.extend(m for m in (model.get("metrics") or []) if isinstance(m, dict) and m.get("name"))
            glossary.extend(_glossary_entries(model))

        header_kw = dict(
            generated_at=generated_at,
            content_hash=row.get("content_hash") or "",
            source_slug=slug,
            ttl_seconds=ttl_seconds,
        )
        yaml_header = _yaml_header(**header_kw)
        md_header = _md_header(**header_kw)

        files[f"{slug}/_brief.md"] = md_header + "\n" + _brief_body(row, models, datasets, metrics)

        for dataset in datasets:
            dname = str(dataset["name"]).strip()
            if not dname:
                continue
            files[f"{slug}/tables/{dname}.yml"] = yaml_header + _dump_yaml(dataset)

        for metric in metrics:
            mname = str(metric["name"]).strip()
            if not mname:
                continue
            files[f"{slug}/metrics/{mname}.yml"] = yaml_header + _dump_yaml(metric)

        if glossary:
            files[f"{slug}/glossary.md"] = md_header + "\n" + _glossary_body(glossary)

    return files
