"""resource_source_tags — "this skill / agent / knowledge domain is about THAT source"

PG-ONLY (A3 PG-first ratchet — ``CLAUDE.md`` -> "Dual-backend discipline").
There is deliberately NO matching ``_vN_to_v(N+1)`` step in ``src/db.py`` and
``SCHEMA_VERSION`` stays at ``FROZEN_DUCKDB_SCHEMA_VERSION``: the DuckDB
app-state backend is frozen, so this table exists on Postgres only and its
repository (``src/repositories/resource_source_tags_pg.py``) has no DuckDB
sibling. A DuckDB-backed instance reaching the feature gets the typed
``501 requires_postgres_backend``. See ``docs/migrations.md`` -> "Adding a
PG-only feature (post-A3)".

Autogenerated with ``alembic revision --autogenerate`` off
``src/models/semantic_coverage.py``; the body below is that output verbatim,
renamed to the repo's sequential revision-id convention. ``downgrade()`` is
the true inverse — the table is new, so dropping it restores the previous
schema exactly.

Revision ID: 0073_resource_source_tags
Revises: 0072_sync_state_id_v124
Create Date: 2026-08-26
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0073_resource_source_tags"
down_revision: Union[str, None] = "0072_sync_state_id_v124"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "resource_source_tags",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("tagged_by", sa.String(), nullable=True),
        sa.Column(
            "tagged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_type", "resource_id", "source_id", name="uq_resource_source_tags_triple"),
    )
    op.create_index("idx_resource_source_tags_source", "resource_source_tags", ["source_id"], unique=False)


def downgrade() -> None:
    op.drop_index("idx_resource_source_tags_source", table_name="resource_source_tags")
    op.drop_table("resource_source_tags")
