"""semantic_feedback — "this answer looked wrong", from a person or an agent

PG-ONLY (A3 PG-first ratchet — ``CLAUDE.md`` -> "Dual-backend discipline").
There is deliberately NO matching ``_vN_to_v(N+1)`` step in ``src/db.py`` and
``SCHEMA_VERSION`` stays at ``FROZEN_DUCKDB_SCHEMA_VERSION``: the DuckDB
app-state backend is frozen, so this table exists on Postgres only and its
repository (``src/repositories/semantic_feedback_pg.py``) has no DuckDB
sibling. A DuckDB-backed instance reaching the feature — from the UI, chat,
MCP or CLI — gets the typed ``501 requires_postgres_backend``. See
``docs/migrations.md`` -> "Adding a PG-only feature (post-A3)".

Autogenerated with ``alembic revision --autogenerate`` off
``src/models/semantic_feedback.py``; the body below is that output verbatim,
renamed to the repo's sequential revision-id convention. ``downgrade()`` is
the true inverse — the table is new, so dropping it restores the previous
schema exactly.

Revision ID: 0074_semantic_feedback
Revises: 0073_resource_source_tags
Create Date: 2026-08-26
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0074_semantic_feedback"
down_revision: Union[str, None] = "0073_resource_source_tags"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semantic_feedback",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("sql", sa.Text(), nullable=True),
        sa.Column("metric_id", sa.String(), nullable=True),
        sa.Column("model_content_hash", sa.String(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_semantic_feedback_status", "semantic_feedback", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_semantic_feedback_status", table_name="semantic_feedback")
    op.drop_table("semantic_feedback")
    # ### end Alembic commands ###
