"""resource_source_tags — "this skill / agent / knowledge domain is about THAT source"

PG-ONLY (A3 PG-first ratchet — ``CLAUDE.md`` -> "Dual-backend discipline").
There is deliberately NO matching ``_vN_to_v(N+1)`` step in ``src/db.py`` and
``SCHEMA_VERSION`` stays at ``FROZEN_DUCKDB_SCHEMA_VERSION``: the DuckDB
app-state backend is frozen, so this table exists on Postgres only and its
repository (``src/repositories/resource_source_tags_pg.py``) has no DuckDB
sibling. A DuckDB-backed instance reaching the feature gets the typed
``501 requires_postgres_backend``. See ``docs/migrations.md`` -> "Adding a
PG-only feature (post-A3)".

Autogenerated with ``alembic revision --autogenerate`` off
``src/models/semantic_coverage.py``; the body below is that output verbatim,
renamed to the repo's sequential revision-id convention. ``downgrade()`` is
the true inverse — the table is new, so dropping it restores the previous
schema exactly.

Revision ID: 0087_resource_source_tags
Revises: 0086_semantic_draft_pending
Create Date: 2026-08-26

Re-chained (not renamed) TWICE, both times when this branch merged ``main``,
and both times for the identical reason: a revision landing on ``main``
claimed the same parent this file's ``down_revision`` pointed at, forking
the chain into two Alembic HEADS (``upgrade head`` refuses to pick between
them). First re-chain: onto ``0073_agent_scope_granted_by``, which had
landed off the same ``0072`` parent this file originally revised. Second
re-chain (this one): ``0073_column_metadata_source_ref_v125`` had ALSO
landed off ``0073_agent_scope_granted_by`` — via a separate, already-merged
``main`` feature (semantic-phase5) — extending it to
``0074_semantic_draft_pending`` before this file's first re-chain ever
reached `main`, so pointing at ``0073_agent_scope_granted_by`` was already
stale the moment it was written. Re-chained onto the chain's actual current
tip instead of guessing at another single parent, since a THIRD unrelated
chain landing on the same parent again would only repeat the fork. The
revision ID is unchanged so an instance that already applied this table
does not re-run it; only its parent moved, twice.

Third re-chain (F3 merge): the same two migrations this file's parent chain
runs through were RENUMBERED — ``0073_column_metadata_source_ref_v125`` ->
``0075_column_meta_source_ref`` and ``0074_semantic_draft_pending`` ->
``0075_semantic_draft_pending`` — so that the semantic chain hangs off
``0074_llm_usage_caller_user_id`` (the tip ``main`` actually landed) rather
than forking from ``0073_agent_scope_granted_by`` a second time. Same
migrations, same order, new ids; this file followed its parent to the new id.
Revision ID still unchanged at that point, for the same reason as the first
two.

Fourth re-chain (``integration`` merge, landing-plan step 0): the whole
semantic chain — this file included — was renumbered to ``0085``..``0090``
and appended after ``integration``'s ``0079_sso_login``..
``0084_fact_alias_sources``, so this file's id moved
``0073_resource_source_tags`` -> ``0087_resource_source_tags`` and its parent
``0076_semantic_draft_pending`` -> ``0086_semantic_draft_pending``. Unlike
the first three, THIS one does change the revision ID: see the chain root
``0085_column_meta_source_ref`` for the full account and the re-stamp note
for a development database already sitting on an old id.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0087_resource_source_tags"
down_revision: Union[str, None] = "0086_semantic_draft_pending"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "resource_source_tags",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("tagged_by", sa.String(), nullable=True),
        sa.Column(
            "tagged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_type", "resource_id", "source_id", name="uq_resource_source_tags_triple"),
    )
    op.create_index("idx_resource_source_tags_source", "resource_source_tags", ["source_id"], unique=False)


def downgrade() -> None:
    op.drop_index("idx_resource_source_tags_source", table_name="resource_source_tags")
    op.drop_table("resource_source_tags")
