"""semantic_health_mutes — silencing a check is a signature, never a silence

PG-ONLY (A3 PG-first ratchet — ``CLAUDE.md`` -> "Dual-backend discipline").
There is deliberately NO matching ``_vN_to_v(N+1)`` step in ``src/db.py`` and
``SCHEMA_VERSION`` stays at ``FROZEN_DUCKDB_SCHEMA_VERSION``: the DuckDB
app-state backend is frozen, so this table exists on Postgres only and its
repository (``src/repositories/semantic_health_mutes_pg.py``) has no DuckDB
sibling. A DuckDB-backed instance reaching the feature — from the UI, CLI or
MCP — gets the typed ``501 requires_postgres_backend``. See
``docs/migrations.md`` -> "Adding a PG-only feature (post-A3)".

Autogenerated with ``alembic revision --autogenerate`` off
``src/models/semantic_health_mutes.py``; the body below is that output
verbatim, renamed to the repo's sequential revision-id convention.
``downgrade()`` is the true inverse — the table is new, so dropping it restores
the previous schema exactly.

Revision ID: 0089_semantic_health_mutes
Revises: 0088_semantic_feedback
Create Date: 2026-08-26
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0089_semantic_health_mutes"
down_revision: Union[str, None] = "0088_semantic_feedback"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semantic_health_mutes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("muted_by", sa.String(), nullable=False),
        sa.Column("muted_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_semantic_health_mutes_scope", "semantic_health_mutes", ["scope"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_semantic_health_mutes_scope", table_name="semantic_health_mutes")
    op.drop_table("semantic_health_mutes")
    # ### end Alembic commands ###
