"""memory_detection_runs — corporate-memory detection run logs (issue #1971
Part 3): the missing observability for the two extractors that write into
`knowledge_items` (the session-transcript verification detector and the
CLAUDE.local.md collector).

PG-ONLY (A3 PG-first ratchet — ``CLAUDE.md`` -> "Dual-backend discipline").
There is deliberately NO matching ``_vN_to_v(N+1)`` step in ``src/db.py`` and
``SCHEMA_VERSION`` stays at ``FROZEN_DUCKDB_SCHEMA_VERSION``: the DuckDB
app-state backend is frozen, so this table exists on Postgres only and its
repository (``src/repositories/memory_detection_runs_pg.py``) has no DuckDB
sibling. A DuckDB-backed instance reaching the feature — from the UI, CLI or
MCP — gets the typed ``501 requires_postgres_backend``. See
``docs/migrations.md`` -> "Adding a PG-only feature (post-A3)".

Autogenerated with ``alembic revision --autogenerate`` off
``src/models/memory_detection_runs.py``; the body below is that output,
renamed to the repo's sequential revision-id convention. ``downgrade()`` is
the true inverse — the table is new, so dropping it restores the previous
schema exactly.

Revision ID: 0095_memory_detection_runs
Revises: 0094_extraction_runs
Create Date: 2026-09-01
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "0095_memory_detection_runs"
down_revision: Union[str, None] = "0094_extraction_runs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_detection_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sessions_scanned", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_proposed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_filtered", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_inserted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_routed_side_domain", sa.Integer(), server_default="0", nullable=False),
        sa.Column("token_usage", JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("policy_fingerprint", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_memory_detection_runs_started_at", "memory_detection_runs", ["started_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_memory_detection_runs_started_at", table_name="memory_detection_runs")
    op.drop_table("memory_detection_runs")
    # ### end Alembic commands ###
