"""sharepoint_connection_state — per-connection crawl/facts bookkeeping
moved off the worker's local disk (horizontal-scale extraction workers).

Before this table, ``connectors/sharepoint/crawler.py`` kept its per-drive
deltaLink + cTag + failed-item map, and ``connectors/sharepoint/
facts_extraction.py`` kept its per-document extraction state, each as a
JSON file under ``${DATA_DIR}/state/sharepoint_<crawl|facts>/
<connection_id>.json``. Jobs are claimed from a shared Postgres queue
(``src/repositories/jobs_pg.py``, ``claim_next`` with ``SKIP LOCKED``), so a
second worker VM could claim a connection's job whose state file lives on
another host's disk — the exact gap ``0094_extraction_runs.py`` names for
run *observability*; this closes the matching gap for run *resume state*.

One row per ``(connection_id, kind)`` — ``kind`` is ``'crawl'`` or
``'facts'``, deliberately two rows rather than one blob: a corrupt facts
pass must never cost the crawl its deltaLinks, and a resync must never
touch the facts corpus's own bookkeeping, the same isolation the two
separate legacy files gave for free. ``payload`` keeps the exact JSON shape
either module already wrote — see ``connectors/sharepoint/state_store.py``
for the backend-selection seam (this table when the active app-state
backend is Postgres, the pre-existing JSON file otherwise — the DuckDB
app-state backend is frozen, A3) and its one-time legacy-file import.

PG-first ratchet (A3): brand-new app-state table, Alembic-only — no matching
DuckDB ``_vN_to_v(N+1)`` step, ``SCHEMA_VERSION`` does not move.

Autogenerated with ``alembic revision --autogenerate`` off
``src/models/sharepoint_state.py``; the body below is that output, renamed
to the repo's sequential revision-id convention. ``downgrade()`` is the
true inverse — the table is new, so dropping it restores the previous
schema exactly.

Revision ID: 0096_sharepoint_connection_state
Revises: 0095_memory_detection_runs
Create Date: 2026-09-02
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "0096_sharepoint_connection_state"
down_revision: Union[str, None] = "0095_memory_detection_runs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "sharepoint_connection_state",
        sa.Column("connection_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('crawl', 'facts')", name="ck_sharepoint_connection_state_kind"),
        sa.PrimaryKeyConstraint("connection_id", "kind"),
    )


def downgrade() -> None:
    op.drop_table("sharepoint_connection_state")
