"""facts_llm_cache — content-hash LLM response cache for the SharePoint
fact-extraction stage (cost-levers spec 2026-09-02, lever B).

PG-ONLY (A3 PG-first ratchet — ``CLAUDE.md`` -> "Dual-backend discipline").
There is deliberately NO matching ``_vN_to_v(N+1)`` step in ``src/db.py``
and ``SCHEMA_VERSION`` stays at ``FROZEN_DUCKDB_SCHEMA_VERSION``: the
DuckDB app-state backend is frozen, so this table exists on Postgres only
and its repository (``src/repositories/facts_llm_cache_pg.py``) has no
DuckDB sibling. A DuckDB-backed instance running fact extraction simply
gets no cache (one log line at pass start), never a crash — see
``docs/migrations.md`` -> "Adding a PG-only feature (post-A3)".

Autogenerated with ``alembic revision --autogenerate`` off
``src/models/facts_llm_cache.py``; the body below is that output, renamed
to the repo's sequential revision-id convention. ``downgrade()`` is the
true inverse — the table is new, so dropping it restores the previous
schema exactly.

Revision ID: 0096_facts_llm_cache
Revises: 0095_memory_detection_runs
Create Date: 2026-09-02
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0096_facts_llm_cache"
down_revision: Union[str, None] = "0095_memory_detection_runs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facts_llm_cache",
        sa.Column("cache_key", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_index("idx_facts_llm_cache_sha256", "facts_llm_cache", ["sha256"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_facts_llm_cache_sha256", table_name="facts_llm_cache")
    op.drop_table("facts_llm_cache")
    # ### end Alembic commands ###
