"""extraction_conditions — fleet-level provider-refusal conditions the
built-in facts-extraction stage cannot retry its way past (TCRD-296
synthesis F.25, gaps #25/#48).

PG-ONLY (A3 PG-first ratchet — ``CLAUDE.md`` -> "Dual-backend discipline").
There is deliberately NO matching ``_vN_to_v(N+1)`` step in ``src/db.py`` and
``SCHEMA_VERSION`` stays at ``FROZEN_DUCKDB_SCHEMA_VERSION``: the DuckDB
app-state backend is frozen, so this table exists on Postgres only and its
repository (``src/repositories/extraction_conditions_pg.py``) has no DuckDB
sibling. A DuckDB-backed instance simply tracks no condition (the writer and
reader both fail clean, never a 500 — see that module's docstring). See
``docs/migrations.md`` -> "Adding a PG-only feature (post-A3)".

Autogenerated with ``alembic revision --autogenerate`` off
``src/models/extraction_conditions.py``; the body below is that output
verbatim, renamed to the repo's sequential revision-id convention.
``downgrade()`` is the true inverse — the table is new, so dropping it
restores the previous schema exactly.

Revision ID: 0104_extraction_conditions
Revises: 0103_crawl_shards
Create Date: 2026-09-04
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0104_extraction_conditions"
down_revision: Union[str, None] = "0103_crawl_shards"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_conditions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), server_default="provider_limit", nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), server_default="", nullable=False),
        sa.Column("region", sa.String(), server_default="", nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("retry_after_s", sa.Integer(), nullable=True),
        sa.Column(
            "first_seen", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("last_seen", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_extraction_conditions_active", "extraction_conditions", ["provider", "cleared_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_extraction_conditions_active", table_name="extraction_conditions")
    op.drop_table("extraction_conditions")
    # ### end Alembic commands ###
